kind: pipeline
name: greeting

steps:
- name: start
  image: alpine
  commands:
  - echo hello
  - echo world

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    repo: qing-long/hello-world
    tags: latest
